export const DISABLE_DEFAULT_PROVIDERS_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_PROVIDERS";
export const DISABLE_DEFAULT_CLIPBOARD_PROVIDER_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_CLIPBOARD_PROVIDER";
export const DISABLE_DEFAULT_KEYBOARD_PROVIDER_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_KEYBOARD_PROVIDER";
export const DISABLE_DEFAULT_MOUSE_PROVIDER_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_MOUSE_PROVIDER";
export const DISABLE_DEFAULT_SCREEN_PROVIDER_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_SCREEN_PROVIDER";
export const DISABLE_DEFAULT_WINDOW_PROVIDER_ENV_VAR =
  "NUT_JS_DISABLE_DEFAULT_WINDOW_PROVIDER";